### PR TITLE
The Text example for the Hack the Wall hack

### PR DESCRIPTION
**Pull request by sctv**
Initial commit.
Pull to Flowdeeps/LED-Matrix

### CODE REVIEW

**Comment by Flowdeeps** [comment]
Thanks Brian but wouldn't it be better to do a PR against the original repository?

**Comment by sctv** [comment]
Yes. Probably.
However  he hasn't merged yours yet. 
And you give feedback current.

**Comment by sctv** [comment]
Should I close this pull request?

**Comment by Flowdeeps** [comment]
No. I'll merge and then submit to the existing upstream PR.

**Pull request closed without merging**
